### PR TITLE
Feat/yaml load

### PR DESCRIPTION
**Pull request by mandresm**
Yaml loader task, to include yaml dictionaries into the `context`. I open it as a draft, to discuss whether this feature is needed, and where it can be improved (i.e. exclude loading dictionaries with first-level lists, include a loader argument...).

### CODE REVIEW

**Comment by uwefladrich** [comment]
Hi @mandresm ,

Thanks for the PR draft, it is an interesting feature!
I would put it into a somewhat wider context, though. There has been another feature on the wishlist, which would go well together with this. My initial thoughts:

First, I would like to connect this to the `base.context` task that already exists instead to create a new, unrelated, task. Mostly because the UI would be clearer, but also because the implementation could take advantage of the similarity of the tasks.
We can add "sub"tasks to `base.context` without changing the UI for the original task. So we could have, for exampel, `base.context.from_yaml` and still have `base.context` unchanged.

Second, there is another useful feature that is needed: It should be possible to set context variables through a dict that is potentially itself stored in the context. This may sound confusing, so here is an example:

```yaml
- base.context:
    user_config:
      foo: 5
# Later, maybe in another file
- base.context:
    foo: 1
    bar: 2
- base.context.from:
    dict: "{{user_config}}"
```
The effect of this extension would be that we are able to better control when context settings take effect. In the example, one can specify a `user_config` that will overwrite the (default) settings at a later stage.

So my suggestions:

1. Keep `base.context` as it is.
2. Add a new `base.context.from` task, which has two possible arguments (for now):
  a. `file`: which reads from a file
  b. `dict`: see above
3. For the file reading, I would not limit to YAML (for the moment). Just implement YAML and give an error if the file cannot be read (and document of course). It would be easy to read other formats (e.g. JSON).

I have started to look at an implementation.

**Comment by mandresm** [comment]
Hi @uwefladrich,

I also like the idea of having it inside the `base.context.from`, it's a much more generalized use of it. Combining the `from` subtask for both files and dicts is also a really go idea :)

**Comment by uwefladrich** [comment]
Hi,

I have been working on this and came up with #77. I hope you don't mind that it comes with a new PR, but the approach was a bit different (and I do not know how to converge two rather different branches in one PR).

I have added the implementation of ``base.context.from`` (with ``file`` and ``dict`` arguments), tests and documentation over there.

Let me know what you think.

**Comment by mandresm** [comment]
Hi!

Yeah, that's no problem at all. I'll have a look at #77, and close this PR.

**Pull request closed without merging**
